---
name: 'Validate'

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1

      - name: 'Install Nix'
        uses: DeterminateSystems/determinate-nix-action@d96678350ffd6a456235832eb11e1c491589b7bb  # v3.21.8

      - name: 'Validate'
        run: nix develop --command bash scripts/validate-renovate-configs.sh

      - name: 'Check flake'
        run: nix flake check --print-build-logs
